server:
  port: ${PORT:8080}
  shutdown: graceful

logging:
  level[net.talaatharb]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
  application:
    name: oauth2-example-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${rest.security.issuer-uri}/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# Security
keycloak:
  host: ${KEYCLOAK_HOST:localhost}
  port: ${KEYCLOAK_PORT:8180}
  realm: sample-realm
  client-id: example-backend
  schema: ${KEYCLOAK_SCEHMA:http}
  token-url: ${keycloak.schema}://${keycloak.host}:${keycloak.port}/realms/${keycloak.realm}/protocol/openid-connect/token
  auth-url: ${keycloak.schema}://${keycloak.host}:${keycloak.port}/realms/${keycloak.realm}/protocol/openid-connect/auth
rest:
  security:
    issuer-uri: ${keycloak.schema}://${keycloak.host}:${keycloak.port}/realms/${keycloak.realm}

springdoc:
  swagger-ui:
    oauth:
      client-id: example-frontend
      client-secret: